version: '3'

services:
  redis-server:
    image: 'redis:5.0-alpine'
    command: redis-server --requirepass devpassword
    volumes:
      - 'redis_data:/data'
    ports:
      - 6379:6379
    networks:
      main_network:
        aliases:
          - redis-server

  amp-sim-server:
    image: amp-sim-server
    build:
      context: ./
      dockerfile: ./amp_simulated_servers/Dockerfile-simulated-servers
    ports:
      - 7599:7599
#    volumes:
#      - "./amp_simulated_servers:/servers"
    networks:
      main_network:
        aliases:
          - amp-sim-server
    environment:
      - JAEGER_SERVICE_NAME=amp-sim-server
      - JAEGER_AGENT_HOST=jaegertracing
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger:5778

  amp-anomaly-models:
    image: amp-anomaly-models
    build:
      context: ./
      dockerfile: amp_anomaly_models/Dockerfile-anamoly-models
#    expose:
#      - 7699
#    volumes:
#      - "./amp_anomaly_models:/models"
    networks:
      main_network:
        aliases:
          - amp-anomaly-models

  amp-model-api:
    image: amp-model-api
    build:
      context: ./
      dockerfile: amp_model_api/Dockerfile-model-api
    ports:
      - 7699:7699
#    volumes:
#      - "./amp_model_api:/servers"
    networks:
      main_network:
        aliases:
          - amp-model-api
    environment:
      - JAEGER_SERVICE_NAME=amp-model-api
      - JAEGER_AGENT_HOST=jaegertracing
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger:5778

  nginx:
    image: webapp-nginx
    build:
      context: ./
      dockerfile: ./amp_model_api/Dockerfile-nginx
#     expose:
#       - 5000
#       - 9545
    ports:
      - 5000:5000
      - 9545:9545
    depends_on:
      - amp-sim-server
      - amp-model-api
    networks:
      main_network:
        aliases:
          - nginx

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./configs/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      main_network:
        aliases:
          - prometheus

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=foobar
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      main_network:
        aliases:
          - grafana

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      main_network:
        aliases:
          - jaegertracing

volumes:
  prometheus_data: {}
  grafana_data: {}
  redis_data: {}

networks:
  main_network:
