FROM nginx:latest

# Remove the default config file /etc/nginx/nginx.conf includes
RUN rm /etc/nginx/conf.d/default.conf
# Write our conf file
COPY ./configs/nginx/flask_server.conf /etc/nginx/conf.d/
