endpoints:
        default:
                mu: 0.2
                sig: 0.3

        main:
                mu: 0.15
                sig: 0.25

        long_delay:
                mu: 0.5
                sig: 1.0

        short_delay:
                mu: 0.05
                sig: 0.01

