version: '0.0.1'

api:
  local:
    prometheus_query: http://localhost:9090/api/v1/query?{}
    metric_names: http://localhost:9090/api/v1/label/__name__/values
    credentials: ["agent", "password"]
    jaeger_query: null
    s3_archive: null
    disk_archive: null

  simulation:
    prometheus_query: http://prometheus:9090/api/v1/query?{}
    metric_names: http://prometheus:9090/api/v1/label/__name__/values
    credentials: ["agent", "password"]
    jaeger_query: null
    s3_archive: null
    disk_archive: null

anomaly_detection_model:
  metric_loop:
    metric_delay: 15

endpoints:
  default:
    mu: 0.2
    sig: 0.3

  main:
    mu: 0.15
    sig: 0.25

  long_delay:
    mu: 0.5
    sig: 1.0

  short_delay:
    mu: 0.05
    sig: 0.01

  downstream:
    host: nginx
    port: 4090
    mu: 0.05
    sig: 0.01
